server:
  port: 8080


spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    suffix: .html
  #数据源连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: C##SPRING_BOOT
    password: ok
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #配置编码格式，默认UTF-8，此处不配置也可
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    port: 6379
    host: 132.232.154.155
    jedis:
      pool:
        max-active: 60
        min-idle: 0
        max-wait: -1
        max-idle: 60
    timeout: 0




#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #mybatis mapper的配置文件
  type-aliases-package: net.huadong.entity #实体类的包
  configuration:
    map-underscore-to-camel-case: true
#通用mapper
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: ORACLE
  ORDER: BEFORE

#pagehelper分页插件
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志配置
logging:
  level:
    net.huadong: debug
